# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90

podDisruptionBudget:
  enabled: true
  maxUnavailable: 50%
